# Porta deste backend
server.port=${SERVER_PORT:8081}
application.brand.name=AndesCore Software
mail.from=andescoresoftware@gmail.com
mail.logo.url=https://www.andescoresoftware.com.br/AndesCore.jpg

# Mongo Atlas
spring.data.mongodb.uri=${MONGODB_URI}

# RabbitMQ (URI única) ? usado pelo listener opcional
spring.rabbitmq.addresses=${RABBITMQ_URL}
spring.rabbitmq.queue=${RABBITMQ_QUEUE:incident_queue}

# E-mail (Gmail App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.test-connection=false
