global:
  scrape_interval: 60s

scrape_configs:
  - job_name: ticket-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - ticket-backend:8080

remote_write:
  - url: ${GRAFANA_CLOUD_PROMETHEUS_REMOTE_WRITE_URL}
    basic_auth:
      username: ${GRAFANA_CLOUD_PROMETHEUS_USER}
      password: ${GRAFANA_CLOUD_PROMETHEUS_API_KEY}