server.port=8080
spring.application.name=ticket-backend

spring.rabbitmq.addresses=${RABBITMQ_URL}
spring.rabbitmq.queue=${RABBITMQ_QUEUE:incident_queue}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.queue=${spring.rabbitmq.queue}

management.tracing.enabled=true
management.tracing.sampling.probability=${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
management.otlp.tracing.endpoint=${GRAFANA_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.tracing.headers.Authorization=${GRAFANA_OTLP_AUTHORIZATION:}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
